// ==UserScript==
// @name         GeoFS Airport Announcer (final)
// @namespace    https://github.com/yourname
// @version      1.2.1
// @description  Airport announcement addon for GeoFS — enter flight number and destination and trigger boarding, pre-boarding and final call announcements using the browser narrator (Web Speech API). Optional pre-announce beep/countdown; default custom beep URL provided.
// @author       Generated by assistant
// @match        https://geo-fs.com/geofs.php*
// @match        https://*.geo-fs.com/geofs.php*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

(function () {
  'use strict';

  // Default custom beep URL provided by user
  const DEFAULT_CUSTOM_BEEP = 'https://github.com/blueaviation024/GeoFS-Airport-Announcer/raw/refs/heads/main/Ding%20dong%20airport%20attention%20sound%20-%20My%20HD%20sound%20FX.mp3';

  // Utility: safe DOM create
  function el(tag, attrs = {}, children = []) {
    const e = document.createElement(tag);
    for (const k in attrs) {
      if (k === 'style') Object.assign(e.style, attrs[k]);
      else if (k.startsWith('on') && typeof attrs[k] === 'function') e.addEventListener(k.substring(2), attrs[k]);
      else e.setAttribute(k, attrs[k]);
    }
    children.forEach(c => (typeof c === 'string' ? e.appendChild(document.createTextNode(c)) : e.appendChild(c)));
    return e;
  }

  // Make UI container
  const container = el('div', {
    id: 'gfs-announcer',
    style: {
      position: 'fixed',
      right: '12px',
      bottom: '12px',
      width: '380px',
      zIndex: 999999,
      fontFamily: 'Segoe UI, Roboto, Arial, sans-serif',
      boxShadow: '0 6px 18px rgba(0,0,0,.25)'
    }
  });

  const style = el('style', {}, [`
    #gfs-announcer .panel { background: rgba(6,22,36,0.95); color: #e6eef6; padding: 10px; border-radius: 8px; }
    #gfs-announcer input, #gfs-announcer select { width: 100%; box-sizing: border-box; margin: 4px 0; padding: 6px 8px; border-radius: 4px; border: 1px solid #2b3b4a; background: #0f1b26; color: #e6eef6 }
    #gfs-announcer .row { display:flex; gap:8px; }
    #gfs-announcer button { background: linear-gradient(#2a8bd6,#1b6fb0); color: white; border: none; padding: 8px; border-radius: 6px; cursor: pointer; flex: 1 }
    #gfs-announcer button.secondary { background: linear-gradient(#4a4a4a,#2e2e2e) }
    #gfs-announcer .small { font-size: 12px; opacity: 0.9 }
    #gfs-announcer .log { margin-top:8px; font-size:12px; color:#cfe8ff; max-height:72px; overflow:auto; background: rgba(255,255,255,0.02); padding:6px; border-radius:4px }
  `]);

  const panel = el('div', { class: 'panel' }, []);

  // Collapsible header (title + collapse button)
  const headerRow = el('div', { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' } }, []);
  const titleElem = el('div', { style: { fontWeight: 700 } }, ['GeoFS Airport Announcer']);
  const collapseBtn = el('button', { id: 'gfs-collapse', title: 'Hide announcer', style: { marginLeft: '8px', padding: '4px 8px', fontSize: '12px' } }, ['Hide']);
  headerRow.appendChild(titleElem);
  headerRow.appendChild(collapseBtn);

  const flightInput = el('input', { type: 'text', placeholder: 'Flight number (e.g. AB123)', id: 'gfs-flight' });
  const destinationInput = el('input', { type: 'text', placeholder: 'Destination (e.g. JFK)', id: 'gfs-dest' });

  const controls = el('div', { class: 'row' }, []);

  const btnPre = el('button', { id: 'gfs-pre' }, ['Pre-boarding']);
  const btnBoard = el('button', { id: 'gfs-board' }, ['Boarding']);
  const btnFinal = el('button', { id: 'gfs-final' }, ['Final call']);

  const voiceSelect = el('select', { id: 'gfs-voice' }, []);
  const rateInput = el('input', { id: 'gfs-rate', type: 'range', min: '0.6', max: '1.6', step: '0.1', value: '1' });
  const volumeInput = el('input', { id: 'gfs-volume', type: 'range', min: '0', max: '1', step: '0.1', value: '1' });

  const settingsDiv = el('div', { style: { marginTop: '8px' } }, []);
  settingsDiv.appendChild(el('div', { class: 'small' }, ['Voice:']));
  settingsDiv.appendChild(voiceSelect);
  settingsDiv.appendChild(el('div', { class: 'small' }, ['Rate:']));
  settingsDiv.appendChild(rateInput);
  settingsDiv.appendChild(el('div', { class: 'small' }, ['Volume:']));
  settingsDiv.appendChild(volumeInput);
  // Beep controls
  const beepRow = el('div', { class: 'row', style: { marginTop: '6px', alignItems: 'center' } }, []);
  const beepCheckbox = el('input', { type: 'checkbox', id: 'gfs-beep' });
  const beepLabel = el('div', { class: 'small', style: { flex: '1' } }, []);
  beepLabel.appendChild(document.createTextNode('Beep before announcement'));
  const countdownInput = el('input', { id: 'gfs-countdown', type: 'number', min: '0', max: '10', value: '1', style: { width: '64px' } });
  const countdownLabel = el('div', { class: 'small' }, ['Countdown (s)']);
  beepRow.appendChild(beepCheckbox);
  beepRow.appendChild(beepLabel);
  beepRow.appendChild(countdownLabel);
  beepRow.appendChild(countdownInput);
  settingsDiv.appendChild(beepRow);

  // Custom beep URL
  const customRow = el('div', { style: { marginTop: '6px' } }, []);
  const useCustomLabel = el('label', { class: 'small', style: { display: 'flex', gap: '8px', alignItems: 'center' } }, []);
  const useCustomCheckbox = el('input', { type: 'checkbox', id: 'gfs-use-custom' });
  useCustomLabel.appendChild(useCustomCheckbox);
  useCustomLabel.appendChild(document.createTextNode('Use custom beep URL'));
  const customUrlInput = el('input', { type: 'text', id: 'gfs-beep-url', placeholder: 'https://example.com/beep.mp3' });
  customRow.appendChild(useCustomLabel);
  customRow.appendChild(customUrlInput);
  settingsDiv.appendChild(customRow);

  const log = el('div', { class: 'log', id: 'gfs-log' }, ['Ready.']);

  controls.appendChild(btnPre);
  controls.appendChild(btnBoard);
  controls.appendChild(btnFinal);

  panel.appendChild(headerRow);
  panel.appendChild(flightInput);
  panel.appendChild(destinationInput);
  panel.appendChild(controls);
  panel.appendChild(settingsDiv);
  panel.appendChild(log);

  container.appendChild(style);
  container.appendChild(panel);
  // Small open button shown when collapsed
  const openBtn = el('button', { id: 'gfs-open', title: 'Open announcer', style: { display: 'none', position: 'fixed', right: '12px', bottom: '12px', zIndex: 1000000, padding: '6px 10px', borderRadius: '6px', background: '#2a8bd6', color: '#fff', cursor: 'pointer' } }, ['Announcer']);
  container.appendChild(openBtn);
  document.body.appendChild(container);

  // Setup voices
  let voices = [];
  function populateVoices() {
    voices = speechSynthesis.getVoices() || [];
    voiceSelect.innerHTML = '';
    voices.forEach((v, i) => {
      const o = document.createElement('option');
      o.value = i;
      o.textContent = `${v.name} ${v.lang ? '(' + v.lang + ')' : ''}`;
      voiceSelect.appendChild(o);
    });
    // If none, add a placeholder
    if (voices.length === 0) {
      const o = document.createElement('option');
      o.value = -1;
      o.textContent = 'Default system voice';
      voiceSelect.appendChild(o);
    }
  }

  populateVoices();
  window.speechSynthesis.onvoiceschanged = populateVoices;

  function logMsg(txt) {
    const time = new Date().toLocaleTimeString();
    const line = document.createElement('div');
    line.textContent = `[${time}] ${txt}`;
    log.appendChild(line);
    log.scrollTop = log.scrollHeight;
  }

  function speak(text) {
    if (!('speechSynthesis' in window)) {
      alert('Speech synthesis not supported in this browser.');
      return;
    }
    speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    const idx = parseInt(voiceSelect.value, 10);
    if (!isNaN(idx) && voices[idx]) u.voice = voices[idx];
    u.rate = parseFloat(rateInput.value) || 1;
    u.volume = parseFloat(volumeInput.value) || 1;
    u.pitch = 1;
    speechSynthesis.speak(u);
    logMsg(text);
  }

  // WebAudio beep generator
  let audioCtx = null;
  function getAudioCtx() {
    if (!audioCtx) {
      try { audioCtx = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) { audioCtx = null; }
    }
    return audioCtx;
  }

  function playBeep(duration = 200, freq = 1000, type = 'sine') {
    const ctx = getAudioCtx();
    if (!ctx) return Promise.resolve();
    const o = ctx.createOscillator();
    const g = ctx.createGain();
    o.type = type;
    o.frequency.value = freq;
    g.gain.value = 0.0001;
    o.connect(g);
    g.connect(ctx.destination);
    const now = ctx.currentTime;
    g.gain.setValueAtTime(0.0001, now);
    g.gain.exponentialRampToValueAtTime(0.2, now + 0.01);
    o.start(now);
    g.gain.exponentialRampToValueAtTime(0.0001, now + duration / 1000);
    return new Promise(res => { setTimeout(() => { try { o.stop(); } catch(e){}; res(); }, duration + 20); });
  }

  // Play audio from URL (returns when ended or on error)
  function playAudioUrl(url) {
    return new Promise((res) => {
      try {
        const a = new Audio(url);
        a.crossOrigin = 'anonymous';
        a.volume = parseFloat(volumeInput.value) || 1;
        a.addEventListener('ended', () => res());
        a.addEventListener('error', () => res());
        const p = a.play();
        if (p && typeof p.then === 'function') {
          p.then(() => {/* playing */}).catch(() => {/* ignore */});
        }
        // Fallback: if neither ended nor error fires within 3s, resolve to avoid blocking
        setTimeout(() => res(), 3000);
      } catch (e) {
        res();
      }
    });
  }

  async function announceWithOptionalBeep(text) {
    const beepEnabled = !!beepCheckbox.checked;
    const countdown = Math.max(0, parseInt(countdownInput.value, 10) || 0);
    const useCustom = !!useCustomCheckbox.checked;
    const customUrl = (customUrlInput.value || '').trim();
    if (!beepEnabled || countdown <= 0) {
      speak(text);
      return;
    }
    // Play countdown beeps: one per second, then speak
    if (useCustom && customUrl) {
      for (let s = countdown; s > 0; s--) {
        await playAudioUrl(customUrl);
        await new Promise(r => setTimeout(r, 300));
      }
    } else {
      for (let s = countdown; s > 0; s--) {
        await playBeep(140, 1200);
        await new Promise(r => setTimeout(r, 700));
      }
    }
    // small pause then speak
    await new Promise(r => setTimeout(r, 200));
    speak(text);
  }

  function getFlight() { return flightInput.value.trim(); }
  function getDestination() { return destinationInput.value.trim(); }

  // Initialize defaults: set custom URL and enable use
  customUrlInput.value = DEFAULT_CUSTOM_BEEP;
  useCustomCheckbox.checked = true;
  // enable beep by default with a short countdown
  beepCheckbox.checked = true;
  countdownInput.value = '1';

  btnPre.addEventListener('click', () => {
    const f = getFlight();
    if (!f) { alert('Please enter a flight number.'); flightInput.focus(); return; }
    const dest = getDestination();
    const destText = dest ? ` to ${dest}` : '';
    const text = `Attention please. Pre-boarding for flight ${f}${destText}. Passengers requiring extra time or assistance and those traveling with small children may now proceed to the gate.`;
    announceWithOptionalBeep(text);
  });

  btnBoard.addEventListener('click', () => {
    const f = getFlight();
    if (!f) { alert('Please enter a flight number.'); flightInput.focus(); return; }
    const dest = getDestination();
    const destText = dest ? ` to ${dest}` : '';
    const text = `Now boarding flight ${f}${destText}. Passengers in groups one through four, please board now.`;
    announceWithOptionalBeep(text);
  });

  btnFinal.addEventListener('click', () => {
    const f = getFlight();
    if (!f) { alert('Please enter a flight number.'); flightInput.focus(); return; }
    const dest = getDestination();
    const destText = dest ? ` to ${dest}` : '';
    const text = `Final call for flight ${f}${destText}. This is the final boarding call. The gate will be closing shortly. All remaining passengers, please proceed immediately.`;
    announceWithOptionalBeep(text);
  });

  // Keyboard shortcuts: Alt+1 Pre, Alt+2 Board, Alt+3 Final
  window.addEventListener('keydown', (ev) => {
    if (!ev.altKey) return;
    if (ev.key === '1') btnPre.click();
    if (ev.key === '2') btnBoard.click();
    if (ev.key === '3') btnFinal.click();
  });

  // Prevent key/wheel events from bubbling to the page (GeoFS controls) while typing in our UI.
  // Allow Alt+1/2/3 so shortcuts still work when typing.
  function stopKeyEvents(e) {
    try {
      const k = e.key;
      if (e.altKey && (k === '1' || k === '2' || k === '3')) {
        // allow our shortcuts
        return;
      }
    } catch (err) {
      // ignore
    }
    e.stopPropagation();
    // Do not call preventDefault so typing remains functional.
  }

  function addStopPropagationFor(elm) {
    ['keydown', 'keyup', 'keypress', 'input'].forEach(n => elm.addEventListener(n, stopKeyEvents));
    // For range sliders and inputs, prevent wheel from affecting page
    elm.addEventListener('wheel', (ev) => { ev.stopPropagation(); });
  }

  // Attach to interactive elements
  [flightInput, destinationInput, voiceSelect, rateInput, volumeInput, beepCheckbox, countdownInput, useCustomCheckbox, customUrlInput, collapseBtn, openBtn].forEach(addStopPropagationFor);

  // Collapsible behavior
  const STORAGE_KEY = 'gfs_announcer_collapsed_v1';
  function setCollapsed(collapsed) {
    if (collapsed) {
      // hide panel content but keep open button visible
      panel.style.display = 'none';
      openBtn.style.display = 'block';
      collapseBtn.textContent = 'Show';
    } else {
      panel.style.display = '';
      openBtn.style.display = 'none';
      collapseBtn.textContent = 'Hide';
    }
    try { localStorage.setItem(STORAGE_KEY, collapsed ? '1' : '0'); } catch (e) {}
  }

  collapseBtn.addEventListener('click', (ev) => { ev.stopPropagation(); const cur = panel.style.display !== 'none'; setCollapsed(cur); });
  openBtn.addEventListener('click', (ev) => { ev.stopPropagation(); setCollapsed(false); });

  // initialize collapsed state from storage
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    if (v === '1') setCollapsed(true);
  } catch (e) {}

  // Small hint
  logMsg('Shortcuts: Alt+1 Pre-boarding, Alt+2 Boarding, Alt+3 Final call.');

})();